# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'CUSTOMER'), (2, 'EXECUTOR')], default=2, verbose_name='Тип пользователя'),
        ),
    ]
