# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[(1, 'CUSTOMER'), (2, 'EXECUTOR')], default=2, max_length=255, verbose_name='Тип пользователя'),
        ),
    ]
