# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170920_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'Customer'), (2, 'Executor')], default=2, verbose_name='Тип пользователя'),
        ),
    ]
