# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'Заказчик'), (2, 'Исполнитель')], default=2, verbose_name='Тип пользователя'),
        ),
    ]
