# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 09:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20170919_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='money',
            new_name='cost',
        ),
    ]
